[package]
name = "egui-gdtf-inspector"
version = "0.1.0"
authors = ["Johannes Fried <jcmf.schule@gmail.com>"]
edition = "2021"

[dependencies]
eframe = "0.15.0" # Gives us egui, epi and web+native backends