[package]
name = "egui-gdtf-inspector"
version = "0.1.0"
authors = ["Johannes Fried <jcmf.schule@gmail.com>"]
edition = "2021"

[dependencies]
eframe = "0.16.0" # Gives us egui, epi and web+native backends
rfd = "0.6.3"
gdtf-parser = { path = "../gdtf_parser" }